name: Spotless Auto-Format
on:
  push:
    branches: [ "master" ]

jobs:
  formatting:
    name: Auto-Format Code
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK 21
        uses: actions/setup-java@v6
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Spotless Apply
        run: |
          chmod +x mvnw
          ./mvnw spotless:apply

      - name: Auto-commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "REF: auto spotless formatting"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
